# Site settings
title: Node.js, PHP and Python Programming Examples by Alex Swan
email: alex@bold-it.com
description: > # this means to ignore newlines until "baseurl:"
  Alex Swan is a full stack developer currently working at NBCUniversal. 
  He also makes mobile and console games and 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bold-it.com" # the base hostname & protocol for your site
twitter_username: BoldBigflank
github_username:  BoldBigflank

# Build settings
markdown: kramdown
